# Messages templates for issue and pull request
issue:
  message: |
    Hello @@{author} :wave:

    I'm your friendly neighborhood bot and would like to say thank you for filling this issue,
    a maintainer of this repository will come back to you as soon as possible.

    Best regards,

    ~ Hellobot
pull_request:
  message: |
    Hello @@{author} :wave:

    I'm your friendly neighborhood bot and would like to say thank your contribution,
    a maintainer of this repository will come back to you as soon as possible.

    Best regards,

    ~ Hellobot